import requests

url = "https://sandbox.bronid.com/verify"

payload = "{\n    \"metadata\": {\n        \"serviceUuid\": \"yourServiceUuid\",\n        \"secretKey\": \"yourSecretKey\",\n        \"version\": \"1\",\n        \"userId\": \"1\"\n    },\n    \"personal\": {\n        \"firstName\": \"Jane\",\n        \"middleName\": \"Middle\",\n        \"lastName\": \"Citizen\",\n        \"dateOfBirth\": \"30/11/1980\",\n        \"gender\": \"f\",\n        \"email\": \"test@email.com\",\n        \"address\": {\n            \"unitNumber\": \"10\",\n            \"streetNumber\": \"200\",\n            \"streetName\": \"George\",\n            \"streetType\": \"Street\",\n            \"suburb\": \"Sydney\",\n            \"postcode\": \"2000\",\n            \"state\": \"NSW\",\n            \"country\": \"AUS\",\n            \"addressImage\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==\"\n        }\n    },\n    \"driversLicence\": {\n        \"driversLicenceNumber\": \"11111111\",\n        \"driversLicenceState\": \"VIC\",\n        \"driversLicenceExpiryDate\": \"30/11/2020\",\n        \"driversLicenceConsentCheck\": \"checked\",\n        \"driversLicenceImageFront\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==\",\n\t\t\"driversLicenceImageBack\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==\"\n    },\n    \"medicare\": {\n        \"medicareCardColour\": \"green\",\n        \"medicareCardNumber\": \"2111111111\",\n        \"medicareIndividualReferenceNumber\": \"1\",\n        \"medicareNameOnCard\": \"Jane Citizen\",\n        \"medicareExpiryDate\": \"11/2024\",\n        \"medicareConsentCheck\": \"checked\",\n        \"medicareImage\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==\"\n\t},\n    \"passport\": {\n        \"passportNumber\": \"A1111111\",\n        \"passportCountryOfIssue\": \"AUS\",\n        \"passportConsentCheck\": \"checked\",\n        \"passportImage\": \"data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg==\"\n    }\n}"
headers = {'Content-Type': 'application/json'}

response = requests.request("POST", url, data=payload, headers=headers)

print(response.text)
